metrics.nim
It turns out that running an async event loop in its own thread, using the standard library, does not clash with Chronos.
=> HTTP server

benchmarks/bench_collectors.nim, metrics.nim, metrics.nimble, tests/chronicles_tests.nim, tests/main_tests.nim
- retrieving collectors by name string: `counter("foo").inc()` and
`gauge("bar").set(2)`, with implicit object creation
- cleanup benchmarks and add their compilation to the "test" task
=> alternative API

README.md, metrics.nim, metrics.nimble, nim.cfg, tests/chronicles_tests.nim
- avoid a hidden type cast of registered collectors by using generics
- decouple the test suite from Nim config files in parent dirs
- add test compilation without "--threads:on"
=> add default collectors providing process and Nim runtime info

README.md, metrics.nim, tests/main_tests.nim
- switch *_created values to seconds (for OpenMetrics)
- add "_total" to the main counter metric name
- change the default HTTP server port from 9093 to 8000
- changed GC metric names so they are grouped together
- better /proc/self/stat parsing
Review: https://github.com/prometheus/docs/pull/1446
=> Prometheus review changes

metrics.nim
Error
```
[NimScript] exec: nim c --out:./build/all_tests -r -d:release -d:chronicles_log_level=ERROR --verbosity:0 --hints:off --warnings:off -d:usePcreH
eader --passL:"-lpcre" tests/all_tests.nim                                                                                                      
/usr/bin/ld: nimcache/release/all_tests/metrics_metrics.c.o: in function `setGauge_TfFRl69aEiBDwcdgzchxbOQ':                                    
metrics_metrics.c:(.text+0x37c0): undefined reference to `__atomic_store_8'                                                                     
/usr/bin/ld: metrics_metrics.c:(.text+0x37f0): undefined reference to `__atomic_store_8'                                                        
collect2: error: ld returned 1 exit status …
```
=> Workaround for ARMv6

metrics.nim, metrics.nimble, metrics/chronicles_support.nim, tests/chronicles_tests.nim, tests/main_tests.nim
This one is dedicated to you, @mratsim, for noticing that the weak variant is more efficient on ARM.
The rest of the diff is for fixing some weird Nim-1.0.2 breakage that mistakenly gensyms template
parameter names (so `counter.inc(labelValues = labelValues)` ended up as ```inc(myCounter, labelValues`gensym605630 = labelValues`gensym605630)```) - probably https://github.com/nim-lang/Nim/issues/12121
=> use the "weak" version of atomicCompareExchange()

README.md, metrics.nim
This one has labels and covers the top instance types by total heap usage.
Looks like this: ![screenshot](https://i.imgur.com/GXDHJsZ.png)
=> new default metric: nim_gc_heap_instance_occupied_bytes

metrics.nim
Something made it possible for "pushMetrics()" to be declared after being used in some generic procs, but that kind of mysterious code reordering can be broken when a gauge is set from a generic proc and the moon is in waxing crescent.
=> move sections around so we have the right proc declaration order

README.md, metrics/chronos_httpserver.nim, metrics/stdlib_httpserver.nim
Calling `/metrics` as a healthcheck is too verbose and a waste of resources.
=> add /health endpoint for a cheap healtcheck

README.md, metrics.nim, tests/main_tests.nim
Fixes https://github.com/status-im/nim-metrics/issues/38
System metrics are now automatically updated when a user-defined metric is changed, in the main thread, if at least 10 seconds passed since the last update. The interval is configurable.
This automation can be disabled, if the API user wants to update system metrics with better regularity, from some event loop.
=> update system metrics from the main thread

README.md, metrics.nim
Those two GC metrics that show thread-specific data got a "thread_id" label and an `updateThreadMetrics()` proc, extracted from `updateSystemMetrics()` so it can be called in multiple threads.
I also added a new metric - `nim_gc_heap_instance_occupied_summed_bytes` - which sums up all the sizes we get from `dumpHeapInstances()`, but it turns out to be smaller than `nim_gc_mem_occupied_bytes` in the main thread:
```text
$ curl -sS http://127.0.0.1:8008/metrics | grep nim_gc | grep -Ev 'created|type_name|^#'
nim_gc_mem_bytes{thread_id="15016"} 1582231552.0
nim_gc_mem_occupied_bytes{thread_id="15016"} 676859760.0
nim_gc_heap_instance_occupied_summed_bytes 634171659.0
```
Do we want to keep it?
=> per-thread GC metrics

metrics.nim
I blame the exception handling ugliness on the compiler who can't figure out that if I'm handling a `CatchableError`, the only `Exception` that can be raised is a `Defect`.
=> update.*Metrics - make them GC-safe

README.md, metrics.nim
A new implementation of custom collectors that can be exposed in the public API, because it hides collector implementation details.
Non thread-specific system metrics have been moved to custom collectors, so they're being updated at collection time.
Docs, examples and tests to follow in another PR.
=> custom collectors 2.0

.github/workflows/ci.yml, README.md, metrics.nim, tests/main_tests.nim
Less code for library users, less code for standard collectors.
I don't think that registering collectors before their metrics or custom fields are initialised is going to cause any problems. It doesn't for `nimbus_beacon_node`.
=> refactor custom collectors

.github/workflows/ci.yml, metrics/chronos_httpserver.nim, tests/chronos_server_tests.nim
This PR adds new interface for chronos HTTP server management, which allows:
1. Start and close metrics HTTP server gracefully.
2. Pause and resume server.
=> Improve chronos metrics HTTP server.

benchmarks/bench_common.nim
Upstream benchmarking code from `nimbus-eth2` was removed:
- https://github.com/status-im/nimbus-eth2/pull/3233
It is not useful to refer to it anymore.
=> Remove outdated upstream reference

.github/workflows/ci.yml
The `.nimble` file already ensures that both `--mm:refc` and `--mm:orc` are passed. If we also set it in `ci.yml` then both options are passed, including the case where they are conflicting.
=> Do not set conflicting `--mm` params

metrics/chronicles_support.nim
why:
missing return code in formatter
=> make chronicles work with metrics logging

README.md, metrics.nim, tests/main_tests.nim
The existing implementation was confused about how running a proc in a thread works - just because there's a pointer involved doesn't mean that a thread-specific version of a proc is used. For the registration to work, one would have to extract a pointer to the per-thread heap that the nim GC uses which is not trivial.
=> clean up per-thread metrics

metrics.nim, metrics.nimble, metrics/chronicles_support.nim, metrics/shseq.nim, tests/main_tests.nim, tests/test_shseq.nim
By allocating label metadata from thread-shared memory, we can allow the creation of new labels from any thread. Though metrics must still be registered from the main thread, general usage after registration becomes more flexible.
A downside of this approach is that memory for labels (and friends) is no longer managed by the GC meaning that it potentially leaks should one wish to release the registry - this does not have much practical impact since registered metrics typically stay around until the application ends but could have an impact on applications using custom registries.
Fixing the leak would require introducing an API for manually releasing the shared resources, an excercise left for the future.
A more forceful refactoring would also make `Collector` non-ref - this would allow …
=> allow creating labels from different threads
